"""This file contains only a dict to merge all categories in
only five.

usage:
from categories import categ
"""

categ = {
    'health_beauty': 'other',
    'computers_accessories': 'high-tech',
    'auto': 'other',
    'bed_bath_table': 'home',
    'furniture_decor': 'home',
    'sports_leisure': 'hobbies',
    'perfumery': 'hobbies',
    'housewares': 'home',
    'telephony': 'high-tech',
    'watches_gifts': 'hobbies',
    'other_drink': 'other',
    'baby': 'other',
    'stationery': 'other',
    'tablets_printing_image': 'high-tech',
    'toys': 'hobbies',
    'fixed_telephony': 'high-tech',
    'garden_tools': 'hobbies',
    'fashion_bags_accessories': 'clothing',
    'small_appliances': 'home',
    'consoles_games': 'high-tech',
    'audio': 'hobbies',
    'fashion_shoes': 'clothing',
    'cool_stuff': 'other',
    'luggage_accessories': 'other',
    'air_conditioning': 'home',
    'construction_tools_construction': 'home',
    'kitchen_dining_laundry_garden_furniture': 'home',
    'costruction_tools_garden': 'home',
    'fashion_male_clothing': 'clothing',
    'pet_shop': 'hobbies',
    'office_furniture': 'hobbies',
    'market_place': 'other',
    'electronics': 'high-tech',
    'home_appliances': 'home',
    'party_supplies': 'home',
    'home_confort': 'home',
    'costruction_tools_tools': 'home',
    'agro_industry_and_commerce': 'other',
    'furniture_mattress_and_upholstery': 'other',
    'books_technical': 'hobbies',
    'home_construction': 'home',
    'musical_instruments': 'hobbies',
    'furniture_living_room': 'home',
    'construction_tools_lights': 'hobbies',
    'industry_commerce_and_business': 'other',
    'other': 'other',
    'art': 'hobbies',
    'furniture_bedroom': 'home',
    'books_general_interest': 'hobbies',
    'construction_tools_safety': 'hobbies',
    'fashion_underwear_beach': 'clothing',
    'fashion_sport': 'clothing',
    'signaling_and_security': 'home',
    'computers': 'high-tech',
    'christmas_supplies': 'hobbies',
    'fashio_female_clothing': 'clothing',
    'home_appliances_2': 'home',
    'books_imported': 'hobbies',
    'drinks': 'other',
    'cine_photo': 'hobbies',
    'la_cuisine': 'home',
    'music': 'hobbies',
    'home_comfort_2': 'home',
    'small_appliances_home_oven_and_coffee': 'home',
    'cds_dvds_musicals': 'hobbies',
    'dvds_blu_ray': 'hobbies',
    'flowers': 'hobbies',
    'arts_and_craftmanship': 'hobbies',
    'diapers_and_hygiene': 'other',
    'fashion_childrens_clothes': 'clothing',
    'security_and_services': 'home'
}
